export const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;
export const SUPABASE_URL = process.env.SUPABASE_URL;
export const NEXT_PUBLIC_FARM_CONTRACT = process.env.NEXT_PUBLIC_FARM_CONTRACT;
export const NEXT_PUBLIC_MULTICALL_CONTRACT =
  process.env.NEXT_PUBLIC_MULTICALL_CONTRACT;
export const NEXT_PUBLIC_CHAIN_ID = process.env.NEXT_PUBLIC_CHAIN_ID;
export const NEXT_PUBLIC_ROUTER_CONTRACT =
  process.env.NEXT_PUBLIC_ROUTER_CONTRACT;
export const NEXT_PUBLIC_FACTORY_CONTRACT =
  process.env.NEXT_PUBLIC_FACTORY_CONTRACT;
export const NEXT_PUBLIC_WEOS_ADDRESS = process.env.NEXT_PUBLIC_WEOS_ADDRESS;
export const NEXT_PUBLIC_RPC = process.env.NEXT_PUBLIC_RPC;
export const NEXT_PUBLIC_BLOCK_EXPLORER =
  process.env.NEXT_PUBLIC_BLOCK_EXPLORER;
export const NEXT_PUBLIC_VAULT_CONTRACT =
  process.env.NEXT_PUBLIC_VAULT_CONTRACT;
export const NEXT_PUBLIC_NEUTRO_TOKEN_CONTRACT =
  process.env.NEXT_PUBLIC_NEUTRO_TOKEN_CONTRACT;
export const NEXT_PUBLIC_XNEUTRO_TOKEN_CONTRACT =
  process.env.NEXT_PUBLIC_XNEUTRO_TOKEN_CONTRACT;
export const NEXT_PUBLIC_DIVIDENDS_CONTRACT =
  process.env.NEXT_PUBLIC_DIVIDENDS_CONTRACT;
export const NEXT_PUBLIC_MASTER_CONTRACT =
  process.env.NEXT_PUBLIC_MASTER_CONTRACT;
export const NEXT_PUBLIC_YIELDBOOSTER_CONTRACT =
  process.env.NEXT_PUBLIC_YIELDBOOSTER_CONTRACT;
export const NEXT_PUBLIC_NEUTRO_HELPER_CONTRACT =
  process.env.NEXT_PUBLIC_NEUTRO_HELPER_CONTRACT;
export const NEXT_PUBLIC_POSITION_HELPER_CONTRACT =
  process.env.NEXT_PUBLIC_POSITION_HELPER_CONTRACT;
export const NEXT_PUBLIC_NFT_POOL_FACTORY_CONTRACT =
  process.env.NEXT_PUBLIC_NFT_POOL_FACTORY_CONTRACT;
export const NEXT_PUBLIC_NITRO_POOL_FACTORY_CONTRACT =
  process.env.NEXT_PUBLIC_NITRO_POOL_FACTORY_CONTRACT;
