export const SUPABASE_SERVICE_KEY = process.env.SUPABASE_SERVICE_KEY;
export const SUPABASE_URL = process.env.SUPABASE_URL;
export const NEXT_PUBLIC_FARM_CONTRACT = process.env.NEXT_PUBLIC_FARM_CONTRACT
