export type Farm = {
  pid: number,
  name: string,
  lpToken: `0x${string}`,
  token0: `0x${string}`,
  token1: `0x${string}`,
  token0decimals: number,
  token1decimals: number,
  token0denominator: number,
  token1denominator: number,
  token0Logo: string,
  token1Logo: string,
  token0gecko: string,
  token1gecko: string,
  token0price: number,
  token1price: number,
  reserves0: string,
  reserves1: string,
  valueReserves0: string,
  valueReserves1: string,
  valueOfLiquidity: string,
  reward: `0x${string}`,
}
